name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Set this to your default branch if it's not 'main'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./golan/Dockerfile
        push: true
        tags: arifislam/golan-action:latest  # Change to your Docker Hub username/repository
